#pragma config(Sensor, in3,    C,              sensorAnalog)
#pragma config(Sensor, in4,    DS,             sensorAnalog)
#pragma config(Sensor, in2,    B,              sensorAnalog)
#pragma config(Sensor, in1,    A,              sensorAnalog)

//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma DebuggerWindows("Sensors")
//!!Code automatically generated by 'ROBOTC' configuration wizard               !!//

task main()
{
	 while(SensorValue[A] == 1)
  {
    if (SensorValue[A]<500)
    { nxtDisplayTextLine (0, "ok");}
  }
}
