
#pragma config(Sensor, in2,    B,              sensorAnalog) //detect ball
#pragma config(Sensor, in3,    C,              sensorAnalog) //detect opponent
#pragma config(Sensor, in4,    A,              sensorAnalog) //short distance sensor
//#pragma config(Sensor, in1,    D,              sensorAnalog) ; not used
//#pragma config(Sensor, dgtl1,  ReflA,          sensorDigitalIn) //Reflective sensors black is 1, yellow is 0 ? check again
//#pragma config(Sensor, dgtl1,  ReflB,          sensorDigitalIn)
//#pragma config(Sensor, dgtl1,  ReflC,          sensorDigitalIn)
//#pragma config(Sensor, dgtl1,  ReflD,          sensorDigitalIn)

//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//declaration variables for detection code
long distancesensorA = 1/SensorValue[A]
long distancesensorB = 1/SensorValue[B]
long distancesensorC = 1/SensorValue[C]
int ball_close=0;
int object_detection=0;
int robot_detection=0;

//declaration variables for gripper


task main()

Equation_distance()
{
	XA=(SensorValue[A]+0.1795)/1.0471
	XB=(SensorValue[B]-0.6685)/0.4255
	XC=(SensorValue[C]+0.6763)/0.5554

}

Action_border() // to move backward; if reach yellow line
{
		if (sensorDigitalIn[ReflA] == 0) ||	(sensorDigitalIn[ReflB] == 0) || (sensorDigitalIn[ReflC] == 0) || (sensorDigitalIn[ReflD] == 0)
	{
		//motor move backward
	}
}

Action_opponent() //to move backward; if detect opponent in front
{
	if (robot_detection==1)
	{
		//motor move backward
}
}

Action_ball()	//move certain cm based on the detected ball
{
	if(object_detection==1)
	{
		//accelerate or decelerate based on distance
	}
}


Gripper_grip() //to lift down catcher (catch the ball) and lift up gripper
{
	if (ball_close==1)
	{

}

}

Gripper_release()	//lift up gripper higher to let ball fall down into box
{

}



Detection_all()
{
	while(true){
		if(250<SensorValue[B]&& SensorValue[B]< 3000) //detect an object ball,small value means long distance
		{
			object_detection =1;

			if (SensorValue[C] >SensorValue[B]-100 && SensorValue[C] <SensorValue[B]+100) // if detect other robot
			{
				robot_detection = 1; //that is robot
			}
			else{
				robot_detection = 0;

				//Detect the ball if it is close to the grabber
				if(robot_detection ==0&&object_detection==1){
					if(SensorValue[A] > SensorValue[B]-230 && SensorValue[A] <SensorValue[B]+230) //robot is closed to the object
					{
						ball_close =1;	//close then rotate the body
					}
					else{
						ball_close = 0; //not close enough
					}
				}
			}
		}

		else{
			object_detection=0;
			robot_detection =0;
			ball_close=0;
		}
  }


}
