#pragma config(Sensor, dgtl1,  RA,             sensorDigitalIn)
#pragma config(Sensor, dgtl2,  RB,             sensorDigitalIn)
#pragma config(Sensor, dgtl3,  RC,             sensorDigitalIn)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma DebuggerWindows("Sensors")
//!!Code automatically generated by 'ROBOTC' configuration wizard               !!//


task main()
{
while(SensorValue[RA] == 1)
  {
    writeDebugStreamLine("dfsdfsdfs %d",SensorValue[RA] == 1);
  }


}
